server:
  port: 8091

eureka:
  instance:
    hostname: eurekaserver1
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver1:8091/eureka/,http://eurekaserver2:8091/eureka/
